### ISSUE TITLE
How To Use SubFormArray ?

### ISSUE THREAD

**Issue by shalkam** [PayloadDev/react-at-rest#19]
Hi, 
I've been trying to find out how to use the subform array element but without any success.
It always shows an empty well.

``` html
<div class="well well-sm"></div>
```

Here is how I use it :

``` html
 <Forms.SubFormArray {...this.getFieldProps('concepts') } >
       <Forms.TextInput {...this.getFieldProps('concept') } />
</Forms.SubFormArray>
```

Regards,
Mostafa

**Comment by fortybillion** [comment]
`SubFormArray` is somewhat undocumented because the details are still being worked on, but the basic idea is you can use it to create/edit Resources that include an array of sub-Resources.

For example, if you have a Company that holds multiple Addresses, the JSON might look something like:

```
{
  "company": {
    "name": "MyCompany",
    "addresses": [
      {
        "name": "Head Office",
        "street": "123 Fake St",
        "city": "Fakeville"
      },
      {
        "name": "Other Office",
        "street": "456 7th Ave",
        "city": "Fakeville"
      }
    ]
  }
}
```

To build out the Form, you'd have your `CompanyForm` containing a `SubFormArray` of `AddressForm`s.

```
<div className='well'>
  <Forms.TextInput {...this.getFieldProps('name') } />
  <Forms.SubFormArray
    {...this.getFieldProps('addresses')}>
    <AddressForm />
  </Forms.SubFormArray>
</div>
```

`AddressForm` would also extend `RestForm` and would render like this:

```
<div>
  <Forms.TextInput
    {...this.getFieldProps('name')}/>
  <Forms.TextInput
    {...this.getFieldProps('street')}/>
  <Forms.TextInput
    {...this.getFieldProps('city')}/>
  <a
    className='btn'
    onClick={this.props.onRemove}>Remove</a>
</div>
```

As I said, SubFormArray is still evolving so let us know if you have any issues with getting it running.

**Comment by shalkam** [comment]
Thanks for your quick reply.
When I've first tried the code it was working only on the edit page not the create page.
I checked out what was difference between the two, And I've found the problem with the `SubFormArray`
By Default when a `SubFormArray` Element is created it adds an empty array with its key to the model, for the example above with the adresses the model will look like this :

``` javascript
{ addresses:[] }
```

As you can see it supplies the model with an empty array corresponding to its key.
But this also doesn't work and I end up with an empty container too with no form elements.

**The Work Around**
Is not to supply the form with an empty model, and load the `SubArrayForm` with an array with an empty object as its first.

``` javascript
componentWillMount() {
  this.setState({ model: { addresss:[{}] } });
}
```

``` javascript
    render() {
        return (
            <Form
                onChange={this.handleChange.bind(this) }
                model={this.state.model}
                store = {this.store}
                onSuccess = {this.handleSuccess.bind(this) } />
        );
    }
```

I hope making SubFormArray load an empty object to the array by default won't be that hard

Second thing, After adding  `SubFormArray`  as the instruction above it doesn't show `Add new item` button ... how to get it to show

**Comment by fortybillion** [comment]
Currently in our code we're passing a thin but not completely empty model into the Create form, like this:

```
<Form model={addresses: [{}]} ... />
```

which will initialize the subform correctly. Not ideal but probably a better workaround than setting it onMount. This is something that'll be corrected as we move towards a final version of SubFormArray.

To get the "New Item" button, pass a button-like component to your `SubFormArray`. It will be initialized with the correct event handlers for creating a new item in the array.

```
button = <button>New Item</button>
<SubFormArray addResourceButton={button} ... />
```

**Comment by shalkam** [comment]
Everything is looking good looks like all it's missing is the documentation

**Comment by shalkam** [comment]
I've edited the react at rest code and changed the default value of the SubFormArray component 
form and empty array `[]` into an array with and empty object `[{}]` and it's working with a completely empty model now no need to add anything.

`react-at-rest/modules/components/form/subform_array.cjsx`

``` coffeescript
 @defaultProps =
    componentTagName:    'div'
    destroyWorkaround:   false
    newItemTemplate:     {}
    permittedProperties: []
  # when singular=true, don't render +/- UI elements
    singular:            false
    value:               [{}]
    wrapperClassName:    'well well-sm'
```

I can create a PR with this if it would help.

**Comment by fortybillion** [comment]
Sure, a PR would be great. Thanks.
