### ISSUE TITLE
How to refetching data in ES6?

### ISSUE THREAD

**Issue by Otetz** [PayloadDev/react-at-rest#20]
My component receives props with query parameters to REST client and needs to re-fetch data from service. 
How will i do it?

**Comment by fortybillion** [comment]
You may need to customize the refetching behaviour of your `DeliveryService` subclass. There's some documentation here that should help: https://github.com/PayloadDev/react-at-rest/blob/master/docs/deliveryservice.md#refetching-data

**Comment by Otetz** [comment]
Those code in CoffeeScript. I don't know this language :(

**Comment by fortybillion** [comment]
Are you using React Router in your project? If so, Delivery Service will automatically re-fetch when the query parameters change.

**Comment by Otetz** [comment]
I don't use React Router.

**Comment by fortybillion** [comment]
Then you'll need to implement your own logic that detects changes in the URL and refetches the data. To do a manual refresh in the `DeliveryService` subclass, you can do the following in `componentWillReceiveProps`:

```
    this.boundResources = []
    this.bindResources(nextProps)
    if (this.boundResources.length) this.getResources()
```

**Comment by Otetz** [comment]
It's working!
Thank you very much! :)
